spring:
  datasource:
    url: jdbc:h2:mem:notasfiscais
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console-notasfiscais
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: commerce-notas-fiscais
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            type:
              mapping: 'vendaEvent:br.com.zup.edu.commercenotasfiscais.events.VendaEvent'
  mail:
    host: localhost
    port: 2525
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8084
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on-param
    include-binding-errors: always
